### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by ltagliamonte-dd** [amazonlinux/amazon-ec2-net-utils#31]
Hello!
Is there a pre-released deb for debian or the only available option is to build it ourself?

**Comment by nmeyerhans** [comment]
We're not publishing .deb packages just yet, but I'd like to start doing so before long. Ideally they'd be in an apt repository, but we could also distribute a prebuilt .deb here on GitHub in the interim if that'd be helpful.

It's on my to-do list to upload the package to the Debian archive directly. I haven't done that yet because the Debian cloud images don't use systemd-networkd for interface management, and installing this package on them would introduce a fairly disruptive change to how the network is set up.  There have been conversations within the Debian cloud team, as well as within Debian more broadly, about possibly changing to systemd-networkd for Debian 12 (bookworm), but no definitive decisions have been made yet. Once a final commitment to systemd-networkd is made, then I think it'll make sense to upload an amazon-ec2-net-utils package.

**Comment by nmeyerhans** [comment]
Opened an ITP at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1026919

**Comment by nmeyerhans** [comment]
The package has been accepted into the archive and should be available in future Debian releases.

Exactly how to integrate it into Debian's public AMIs is not yet decided. You can follow up with the Debian cloud team with suggestions or requests ([contact details on wiki.debian.org](https://wiki.debian.org/Teams/Cloud))
