### ISSUE TITLE
Secondary IPs missed in aliases depending on sort

### ISSUE THREAD

**Issue by jordantoor-cpi** [amazonlinux/amazon-ec2-net-utils#63]
After a bit of debugging, looks like I came across an issue where secondary IPs associated with an ENI are "lesser" than the primary IP, the logic mistakenly aliases to the wrong IP.

To reproduce, attach an ENI with multiple IPs where the second IP comes earlier in the CIDR than the primary, ex:
```
172.20.4.123/22 [primary]
172.20.2.34/22 [secondary]
```

https://github.com/amazonlinux/amazon-ec2-net-utils/blob/8aa082885ab2f7ffb6b6b8a39cbc261e9c3ae53a/lib/lib.sh#L135
Has an assumption that the first IP address is the primary IP (correctly so), so it does not make an extra alias for the primary IP in `ec2net_alias.conf` that gets created.

However, due to the `sort` in `get_iface_imds`, it will get missed and then the primary IP instead gets added to the aliases file.
https://github.com/amazonlinux/amazon-ec2-net-utils/blob/8aa082885ab2f7ffb6b6b8a39cbc261e9c3ae53a/lib/lib.sh#L101

I'm not sure if the sort is being used for other purposes, though it may suffer from some other logic failures since it is a plain sort not accounting for address notation. I believe `local-ipv4s` will always return primary first and then secondaries in order of assignment on the ENI, so the alias logic just needs to receive the list unsorted.

Let me know if there's any other details I can help with.

**Comment by nmeyerhans** [comment]
Confirmed, thanks for reporting this.

**Comment by nmeyerhans** [comment]
> I'm not sure if the sort is being used for other purposes, though it may suffer from some other logic failures since it is a plain sort not accounting for address notation. I believe local-ipv4s will always return primary first and then secondaries in order of assignment on the ENI, so the alias logic just needs to receive the list unsorted.

The sort is there to ensure consistent comparison, so it doesn't need to be any specific sort. We use sort because the IMDS does not guarantee that the results are returned in consistent order. The solution to this issue will be move the `sort` invocation to after the `head -n +2` invocation to ensure that we're only looking at secondary IPv4 addresses. Though technically that's still imperfect, as IMDS also doesn't (publicly, anyway) guarantee that the primary address will always be the first one returned at the `local-ipv4s` key.
