### ISSUE TITLE
2.4.0-1.amzn2023.0.1 breaks docker connectivity inside host

### ISSUE THREAD

**Issue by Blefish** [amazonlinux/amazon-ec2-net-utils#97]
While updating to 2.4.0 of amazon-ec2-net-utils (new AMI released), I found that docker containers with bridge network and published ports are no longer accessible on the host itself. They can be connected to just fine outside of the host. Downgrading to 2.3.0 fixed the problem.

At first glance, I do not understand what might be misconfigured.

How to reproduce:
Instance type: t4g.micro
AMI: amazon/al2023-ami-minimal-2023.2.20231002.0-kernel-6.1-arm64 (amazon-ec2-net-utils-2.4.0-1.amzn2023.0.1.noarch)
```
dnf install docker
docker run -p 5678:80 ealen/echo-server
curl -I --header 'X-ECHO-CODE: 404' <host ip>:5678
```
Connection hangs. Connection outside the host works with both versions of ec2-net-utils.

I'd be happy to give any additional details.

**Comment by nmeyerhans** [comment]
I think I know what's happening...  I suspect it's the first rule, which would be using a private route table to route traffic with the primary interface's source address out the primary ENI.  But when the destinations is on the docker bridge, that shouldn't happen; it should instead be routed according to the entries in the main table that would send that traffic to the docker bridge...

**Comment by krzysztof-bronk** [comment]
We've encountered this issue as well. The following `ip rule` gets added by the latest version of the package:

```
10000:  from <host_ip> lookup 10000 proto static
``` 
possibly due to https://github.com/amazonlinux/amazon-ec2-net-utils/pull/94

This bricks features like Consul Connect proxy health checks, though the problem is much more broad as explained by the OP

**Comment by jnummelin** [comment]
Just as a note, this same thing happens with Kubernetes pods too. A pod CANNOT communicate with e.g. kubelet on the host as the return packets are miss-routed because of the rule `10000`.

@nmeyerhans any guestimate when https://github.com/amazonlinux/amazon-ec2-net-utils/commit/7d61595c055b841d4a64fd3db37ca344316b17e3 will get released as part of new AMI(s)?

**Comment by nmeyerhans** [comment]
It's in the queue for the next scheduled AL2023 release.  If all goes according to plan, expect it the week of Oct. 30.

**Comment by jnummelin** [comment]
Thanks for the update

**Comment by harsimranmaan** [comment]
Observed similar behaviour in https://github.com/k3s-io/k3s/issues/8749

**Comment by StephaniePruna** [comment]
@nmeyerhans Has this fix been released?

**Comment by twz123** [comment]
Yes, the newest AMIs are fine again, as mentioned here:  https://github.com/amazonlinux/amazon-linux-2023/issues/528#issuecomment-1793155681
